import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
  agent any
  environment {
    appName = "variable" 
  }
stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'sudo rm -rf /var/www/html/jenkins-react-app'
                sh 'sudo cp -r ${WORKSPACE}/build/ /var/www/html/jenkins-react-app/'
            }
        }
    }
}  